trigger:
  - main

pool:
  name: SelfHosted
  vmImage: 'windows-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20.x'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'install'

- script: |
    if not exist test-results\coverage mkdir test-results\coverage
  displayName: 'Create test results folder'

- script: |
    npx vitest run --coverage --reporter=default --reporter=junit --outputFile=test-results\junit.xml
  displayName: 'Run Unit Tests and Generate Reports'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results\junit.xml'
    mergeTestResults: true
    testRunTitle: 'React Unit Tests'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'test-results\coverage\cobertura-coverage.xml'
    reportDirectory: 'test-results\coverage'
  condition: succeededOrFailed()